# This is a basic workflow to help you get started with Actions

name: Enforce PR labels

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "HOLD_MERGE" label
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "enforce-label"
  enforce-label:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Contains HOLD_MERGE label        
        if: contains(github.event.pull_request.labels.*.name, 'HOLD_MERGE')      
        run: |
          echo "Do not merge ${{ github.event.pull_request.title }} PR with HOLD_MERGE label "
          required: false
