name: Enforce PR labels

on:
  push:
  # Sequence of patterns matched against refs/heads
    branches:    
      - main
   # types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.0
      with:
        BANNED_LABELS: "HOLD_MERGE"
